//General Types
export const REQUEST_LOADING = 'REQUEST_LOADING'
export const REQUEST_FINISHED = 'REQUEST_FINISHED'
export const GET_REQUEST = 'GET_REQUEST'

export const LOG_OUT = 'LOG_OUT'
export const LOG_IN = 'LOG_IN'

//For Login 
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FINISHED = 'LOGIN_FINISHED'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_FINISHED = 'REGISTER_FINISHED'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const UPDATE_REQUEST = 'UPDATE_REQUEST'
export const UPDATE_FINISHED = 'UPDATE_FINISHED'
export const UPDATE_FAILED = 'UPDATE_FAILED'

//For HomePage
export const GAMELIST_REQUEST = 'GAMELIST_REQUEST'
export const GAMELIST_FINISHED = 'GAMELIST_FINISHED'
export const GAMELIST_FAILED = 'GAMELIST_FAILED'

//For GameDetail
export const GAMEDETAIL_REQUEST = 'GAMEDETAIL_REQUEST'
export const GAMEDETAIL_FINISHED = 'GAMEDETAIL_FINISHED'
export const GAMEDETAIL_FAILED = 'GAMEDETAIL_FAILED'

//For ProfilePage
export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_FINISHED = 'PROFILE_FINISHED'
export const PROFILE_FAILED = 'PROFILE_FAILED'

//For Other User Page
export const OTHER_PROFILE_REQUEST = 'OTHER_PROFILE_REQUEST'
export const OTHER_PROFILE_FINISHED = 'OTHER_PROFILE_FINISHED'
export const OTHER_PROFILE_FAILED = 'OTHER_PROFILE_FAILED'
