//General Types
export const REQUEST_LOADING = 'REQUEST_LOADING'
export const REQUEST_FINISHED = 'REQUEST_FINISHED'
export const GET_REQUEST = 'GET_REQUEST'

export const LOG_OUT = 'LOG_OUT'
export const LOG_IN = 'LOG_IN'

//For Login 
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FINISHED = 'LOGIN_FINISHED'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_FINISHED = 'REGISTER_FINISHED'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const UPDATE_REQUEST = 'UPDATE_REQUEST'
export const UPDATE_FINISHED = 'UPDATE_FINISHED'
export const UPDATE_FAILED = 'UPDATE_FAILED'